[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false


[development]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:1234@localhost/apidatabase"


[production]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:1234@localhost/apidatabase"


[testing]
SQLALCHEMY_DATABASE_URI = "sqlite://"
